// Champion dataset facade for the Draft Companion.
//
// The actual data lives in two files:
//   * champions.curated.js — hand-tuned, authoritative entries.
//   * champions.data.js     — the full ~170-champion roster, generated by
//                             scripts/generate-champions.mjs (curated entries
//                             merged with auto-derived ones for every other
//                             champion in the game).
//
// This module just re-exports that data and provides the lookups + helpers the
// rest of the app uses. It stays self-contained at runtime (no CDN calls) — the
// generator is a build-time tool. To add/refine a champion, edit
// champions.curated.js and run `node scripts/generate-champions.mjs`.
//
// Entry shape: { riotId, name, roles, damage, tags } — see champions.curated.js.

import { CHAMPIONS } from "./champions.data.js";

export { CHAMPIONS };

// Quick lookups for the rest of the app.
export const CHAMPIONS_BY_ID = Object.fromEntries(
  CHAMPIONS.map((c) => [c.riotId, c]),
);

export const CHAMPIONS_BY_NAME = Object.fromEntries(
  CHAMPIONS.map((c) => [c.name.toLowerCase(), c]),
);

export const ROLES = ["TOP", "JUNGLE", "MID", "ADC", "SUPPORT"];

// Display labels for roles (ADC reads as "Bot" on the board).
export const ROLE_LABELS = {
  TOP: "Top",
  JUNGLE: "Jungle",
  MID: "Mid",
  ADC: "Bot",
  SUPPORT: "Support",
};

export function findChampion({ riotId, name }) {
  if (riotId && CHAMPIONS_BY_ID[riotId]) return CHAMPIONS_BY_ID[riotId];
  if (name && CHAMPIONS_BY_NAME[name.toLowerCase()]) {
    return CHAMPIONS_BY_NAME[name.toLowerCase()];
  }
  return null;
}

// Estimate which role a champion is most likely filling on a team, given the
// roles already accounted for by that team's other picks. Greedy: prefer the
// champion's first listed role that isn't taken yet, else its primary role.
// Accepts either a champion object or a {riotId?, name?} lookup shape.
export function estimateRole(champ, usedRoles = []) {
  const c = champ && Array.isArray(champ.roles) ? champ : findChampion(champ || {});
  if (!c) return null;
  const free = c.roles.find((r) => !usedRoles.includes(r));
  return free || c.roles[0];
}
